export const AUDIT_ACTIONS = {
  USER_REGISTERED: "USER_REGISTERED",
  SESSION_REVOKED: "SESSION_REVOKED",
  SESSIONS_REVOKED_ALL: "SESSIONS_REVOKED_ALL",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  FORM_PUBLISHED: "FORM_PUBLISHED",
  FORM_SUBMITTED: "FORM_SUBMITTED",
  SUBMISSION_DELETED: "SUBMISSION_DELETED",
  SUBMISSIONS_EXPORTED: "SUBMISSIONS_EXPORTED",
} as const;
