export const AUTH_CONSTANTS = {
  EMAIL_VERIFICATION_TOKEN_BYTES: 32,
  EMAIL_VERIFICATION_TOKEN_TTL_SECONDS: 60 * 60 * 24,
  RESEND_VERIFICATION_COOLDOWN_SECONDS: 60,

  PASSWORD_RESET_TOKEN_BYTES: 32,
  PASSWORD_RESET_TOKEN_TTL_SECONDS: 60 * 30,
  PASSWORD_RESET_COOLDOWN_SECONDS: 60,

  PASSWORD_RESET_RATE_LIMIT_WINDOW_SECONDS: 15 * 60,
  FORGOT_PASSWORD_MAX_ATTEMPTS_PER_IP: 5,
  FORGOT_PASSWORD_MAX_ATTEMPTS_PER_EMAIL: 3,
  RESET_PASSWORD_MAX_ATTEMPTS_PER_IP: 10,

  CHANGE_PASSWORD_MAX_ATTEMPTS_PER_USER: 5,
  CHANGE_PASSWORD_MAX_ATTEMPTS_PER_IP: 20,

  REFRESH_TOKEN_BYTES: 32,

  LOGIN_RATE_LIMIT_WINDOW_SECONDS: 15 * 60,
  LOGIN_RATE_LIMIT_MAX_ATTEMPTS_PER_IP: 20,
  LOGIN_RATE_LIMIT_MAX_ATTEMPTS_PER_EMAIL: 10,

  LOGIN_FAILURE_TRACKING_TTL_SECONDS: 15 * 60,
  LOGIN_PROGRESSIVE_DELAY_BASE_MS: 1000,
  LOGIN_PROGRESSIVE_DELAY_MAX_MS: 8000,
} as const;