import { PERMISSIONS, type Permission } from "./permissions.js";

export const ROLE_NAMES = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  BUILDER: "BUILDER",
  VIEWER: "VIEWER",
  SUBMISSION_MANAGER: "SUBMISSION_MANAGER",
} as const;

export type RoleName =
  (typeof ROLE_NAMES)[keyof typeof ROLE_NAMES];

export const OWNER_PERMISSIONS: readonly Permission[] = [
  PERMISSIONS.ORGANIZATION_READ,
  PERMISSIONS.ORGANIZATION_UPDATE,

  PERMISSIONS.USER_CREATE,
  PERMISSIONS.USER_READ,
  PERMISSIONS.USER_UPDATE,
  PERMISSIONS.USER_DELETE,

  PERMISSIONS.PROJECT_CREATE,
  PERMISSIONS.PROJECT_READ,
  PERMISSIONS.PROJECT_UPDATE,
  PERMISSIONS.PROJECT_DELETE,

  PERMISSIONS.FORM_CREATE,
  PERMISSIONS.FORM_READ,
  PERMISSIONS.FORM_UPDATE,
  PERMISSIONS.FORM_DELETE,
  PERMISSIONS.FORM_PUBLISH,

  PERMISSIONS.SUBMISSION_CREATE,
  PERMISSIONS.SUBMISSION_READ,
  PERMISSIONS.SUBMISSION_UPDATE,
  PERMISSIONS.SUBMISSION_DELETE,
];